# Generated by Django 4.0.3 on 2022-05-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0002_everside_clinic'),
    ]

    operations = [
        migrations.AddField(
            model_name='everside_nps',
            name='client_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='everside_nps',
            name='client_naics',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='everside_nps',
            name='client_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='everside_nps',
            name='clinic_city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='everside_nps',
            name='clinic_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='everside_nps',
            name='clinic_state',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='everside_nps',
            name='clinic_street',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='everside_nps',
            name='clinic_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='everside_nps',
            name='clinic_zip',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='everside_nps',
            name='member_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='everside_nps',
            name='parent_client_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='everside_nps',
            name='parent_client_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='everside_nps',
            name='provider_category',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='everside_nps',
            name='provider_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='everside_nps',
            name='provider_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='everside_nps',
            name='survey_date',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='everside_nps',
            name='survey_month',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='everside_nps',
            name='survey_number',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='everside_nps',
            name='survey_year',
            field=models.CharField(default='', max_length=100),
        ),
    ]
