# Generated by Django 4.0.3 on 2022-05-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0003_everside_nps_client_id_everside_nps_client_naics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='everside_nps',
            name='question_type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
